## 错误处理

### panic! 宏

#### 概念

当执行 panic! 宏时，程序会打印出一个错误信息，展开并清理栈数据，然后接着退出。如果不需要栈展开，可以选择直接终止：

```
[profile.release]
panic = 'abort'
```


#### 查看 backtrace

可 `RUST_BACKTRACE` 环境变量设置为任何不是 0 的值来获取查看堆栈信息
```bash
RUST_BACKTRACE=1 cargo run
```
启用 debug 标识可以查看更多的堆栈信息。
> 当不使用 --release 参数运行 cargo build 或 cargo run 时 debug 标识会默认启用。


### Result

Result 枚举

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```


#### 使用 match 处理 Result

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => {
            panic!("Problem opening the file: {:?}", error)
        },
    };
}
```

也可以使用 if let 表达式

```rust
if let Err(e) = run(config) {
    println!("Application error: {}", e);

    process::exit(1);
}
```


#### 使用 match 处理 Err

```rust
let f = match f {
    Ok(file) => file,
    Err(error) => match error.kind() {
        ErrorKind::NotFound => match File::create("hello.txt") {
            Ok(fc) => fc,
            Err(e) => panic!("Problem creating the file: {:?}", e),
        },
        other_error => panic!("Problem opening the file: {:?}", other_error),
    },
};
```


#### 使用 unwrap 与 expect

unwrap

```rust
let f = File::open("hello.txt").unwrap();
```

expect

```rust
let f = File::open("hello.txt").expect("Failed to open hello.txt");
```


#### ？运算符

直接返回

```rust
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");

    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
```

简写

```rust
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}
```

除了直接用于返回值外，还可以链式调用

```rust
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();

    File::open("hello.txt")?.read_to_string(&mut s)?;

    Ok(s)
}
```


### main 的另一个返回值

```rust
use std::error::Error;
use std::fs::File;

fn main() -> Result<(), Box<dyn Error>> {
    let f = File::open("hello.txt")?;

    Ok(())
}
```


